name: Send LINE Message

on:
  workflow_dispatch: {}   # 手動觸發事件
  schedule:
    - cron: '0 9 * * *'  # 排程每天早上9點執行（UTC時間）

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to LINE
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
            -d '{
                  "to": "${{ secrets.LINE_USER_ID }}",
                  "messages":[{"type":"text","text":"這是手動測試訊息！"}]
                }'
