name: Send LINE Message

on:
  workflow_dispatch:   # 手動觸發事件
  schedule:
    - cron: '0 9 * * *'  # 也可以排程每天早上9點執行（UTC時間）

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to LINE
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ secrets.l3qfzac8l2x2aNue/YTRAKbimKYIqbQqkuGgTRqk3PebeQRU0d7DEzMrq0zcsrzfVd44TIWjYuBWlMf+zHrlYTJzZC55FUmm2nq+bOq8LY0+uVwOKB0HbjTAMqNq/jOCQs687YeEpzhj+KAMsijspAdB04t89/1O/w1cDnyilFU= }}" \
            -d '{
                  "to": "${{ secrets.Uef360c65c710f997a64c572b40fd8251 }}",
                  "messages":[{"type":"text","text":"這是手動測試訊息！"}]
                }'
